configuration: Release

before_build:
    nuget restore

artifacts:
    path: 'Releases\*.*'
    name: StartLauncherInstaller

os: Visual Studio 2017
install:
    set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%    

deploy:
    description: 'Start Launcher'
    provider: GitHub
    auth_token:
        secure: MidR5T9SuBalncsh2ACJNGHmZzsmGYj3yHt1phhIX1Wlafm0TxRr5fztAfPe7c4d
    artifact: StartLauncherInstaller
    draft: false
    prerelease: false
    on:
        branch: master